### PR TITLE
Luisin

### PR DESCRIPTION
**Pull request by luisgomes01**
New sound effects.

### CODE REVIEW

**Review by filipemelo2002 — CHANGES_REQUESTED** [review]
The audio binaries must be in MP3

**Comment by luisgomes01** [comment]
These ones in specific were in the @DavysonMelo changes.

**Comment by DavysonMelo** [comment]
> These ones in specific were in the @DavysonMelo changes.

You can remove them, I already added all the missing audios with the correct extension

**Comment by luisgomes01** [comment]
Done.

**Review by filipemelo2002 — APPROVED** [review]
LGTM

**Pull request merged**
